// Mocks generated by Mockito 5.3.2 from annotations
// in payhippo/test/modules/authentication/splash/viewmodels/splash_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:payhippo/_core_/data/local/local_storage.dart' as _i2;
import 'package:payhippo/_core_/models/language.dart' as _i5;
import 'package:payhippo/_core_/models/user.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalStorageServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageServiceImpl extends _i1.Mock
    implements _i2.LocalStorageServiceImpl {
  MockLocalStorageServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T? getFromDisk<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getFromDisk,
        [key],
      )) as T?);
  @override
  _i3.Future<bool> saveToDisk<T>(
    String? key,
    T? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToDisk,
          [
            key,
            content,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> deleteFromDisk(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> saveData(
    String? key,
    Object? object,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveData,
          [
            key,
            object,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  dynamic getData(String? key) => super.noSuchMethod(Invocation.method(
        #getData,
        [key],
      ));
  @override
  _i3.Future<bool> saveLoggedInUser(_i4.User? data) => (super.noSuchMethod(
        Invocation.method(
          #saveLoggedInUser,
          [data],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> deleteLoggedInUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteLoggedInUser,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> saveFirstName(String? data) => (super.noSuchMethod(
        Invocation.method(
          #saveFirstName,
          [data],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> saveEmail(String? data) => (super.noSuchMethod(
        Invocation.method(
          #saveEmail,
          [data],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool?> setEnableBiometric(bool? data) => (super.noSuchMethod(
        Invocation.method(
          #setEnableBiometric,
          [data],
        ),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);
  @override
  _i3.Future<bool> setAppFirstLaunch(bool? data) => (super.noSuchMethod(
        Invocation.method(
          #setAppFirstLaunch,
          [data],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setIsVerified({required bool? state}) => (super.noSuchMethod(
        Invocation.method(
          #setIsVerified,
          [],
          {#state: state},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> saveUserLanguage(_i5.Language? data) => (super.noSuchMethod(
        Invocation.method(
          #saveUserLanguage,
          [data],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
